{% set name = "mizani" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "2b15c5e82b4053d6fc4a3124e1e42d3578b483a34c01426c174264df9a1e56a4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.6.0
    - numpy
    - pandas >=0.25.0
    - matplotlib-base >=3.1.1
    - palettable

test:
  imports:
    - mizani
    - mizani.external
    - mizani.tests

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: Scales for Python
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
