{% set name = "mizani" %}
{% set version = "0.3.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4d27fa97476a13dbca946f8f18e127f0abc8410ff412ae3fdd7f16ffa206820d" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas >=0.20.1
    - matplotlib
    - palettable

test:
  imports:
    - mizani
    - mizani.external
    - mizani.tests

about:
  home: https://github.com/has2k1/mizani
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Scales for Python'
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
