{% set name = "mizani" %}
{% set version = "0.9.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "37fd4f4c94bf1158cacf6c14478d87b98a4ff511c57b0cfdc34cbe494385f970" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.0
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.8.0
    - numpy >=1.19.0
    - scipy >=1.5.0
    - pandas >=1.3.5
    - matplotlib-base >=3.5.0
    - palettable
    - backports.zoneinfo  # py<3.9 conda does not properly support environment markers
    - tzdata  # os == windows

test:
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - mizani
    - mizani.external
    - mizani.tests
  source_files:
    - '*'
  commands:
    # The pip version can reported incorrectly if setuptools_scm isn't available
    # at build time
    - pip list | grep -i {{ name }} | grep {{ version }}
    - pip check
    - echo $PWD
    - ls -larth
    # TODO: re-enable when fixed
    # - pytest

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Scales for Python
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
