{% set name = "mizani" %}
{% set version = "0.13.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "e3247ea12c746c8104767d7e42a2d16473173c7bc314f298d8294a58f4653353" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11.0
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.10.0
    - numpy >=1.23.5
    - scipy >=1.8.0
    - pandas >=2.2.0
    - python-dateutil
    - tzdata  # os == windows

test:
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - "tests"
    - "pyproject.toml"
  commands:
    # The pip version can reported incorrectly if setuptools_scm isn't available
    # at build time
    - pip list | grep -i {{ name }} | grep {{ version }}
    - pip check
    - echo $PWD
    - ls -larth
    - pytest

about:
  home: https://github.com/has2k1/mizani
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Scales for Python
  dev_url: https://github.com/has2k1/mizani
  doc_url: https://mizani.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
